void commandList() {
  Serial.println(F("-----------------------------------------------------------------------------------------------------------------------------------"));
  Serial.println(F("                                                            Winbond Flash                                                          "));
  Serial.println(F("                                                      SPIFRAM library test v0.0.1b                                                 "));
  Serial.println(F(" ----------------------------------------------------------------------------------------------------------------------------------"));
  Serial.println(F("                                                                Marzogh                                                            "));
  Serial.println(F("                                                              24.11.2015                                                           "));
  Serial.println(F(" ----------------------------------------------------------------------------------------------------------------------------------"));
  Serial.println(F("                                      (Please make sure your Serial monitor is set to 'No Line Ending')                            "));
  Serial.println(F("                                      *****************************************************************                            "));
  Serial.println(F("                                                                                                                                   "));
  Serial.println(F("                      # Please pick from the following commands and type the command number into the Serial console #              "));
  Serial.println(F("     For example - to write a byte of data, you would have to use the Write Byte function - so type '3' into the serial console.   "));
  Serial.println(F("                                                     --------------------------------                                              "));
  Serial.println();
  Serial.println(F("  1. getID"));
  Serial.print(F("\t\t"));
  Serial.println(F("'1' gets the JEDEC ID of the chip"));
  Serial.println(F("  2. writeByte [address] [offset] [byte]"));
  Serial.print(F("\t\t"));
  Serial.println(F("'2' followed by '100' and then by '224' writes the byte 224 to address 100"));
  Serial.println(F("  3. readByte [address] [offset]"));
  Serial.print(F("\t\t"));
  Serial.println(F("'3' followed by '100' returns the byte from address 100"));
  Serial.println(F("  4. writeWord [address] [offset]"));
  Serial.print(F("\t\t"));
  Serial.println(F("'4' followed by '55' and then by '633' writes the int 633 to address 5"));
  Serial.println(F("  5. readWord [address] [offset]"));
  Serial.print(F("\t\t"));
  Serial.println(F("'5' followed by '200' returns the int from address 200"));
  Serial.println(F("  6. writeStr [address] [offset] [inputString]"));
  Serial.print(F("\t\t"));
  Serial.println(F("'6' followed by '345' and then by 'Test String 1!' writes the String 'Test String 1! to address 345"));
  Serial.println(F("  7. readStr [address] [offset] [outputString]"));
  Serial.print(F("\t\t"));
  Serial.println(F("'7' followed by '2050' reads the String from address 2050 into the outputString"));
  Serial.println(F("  8. readEntireChip"));
  Serial.print(F("\t\t"));
  Serial.println(F("'8' reads entire chip and outputs the data to the serial console"));
  Serial.print(F("\t\t"));
  Serial.println(F("This function is to extract data from a flash chip onto a computer as a text file"));
  Serial.print(F("\t\t"));
  Serial.println(F("Refer to 'Read me.md' in the library for details"));
  Serial.println(F("  9. eraseSector[size]"));
  Serial.print(F("\t\t"));
  Serial.println(F("'9' followed by '547' and then by 800 erases an 800 Byte sector starting at address 547"));
  Serial.println(F("  10. eraseChip"));
  Serial.print(F("\t\t"));
  Serial.println(F("'10' erases the entire chip"));
  Serial.println(F(" ----------------------------------------------------------------------------------------------------------------------------------"));
}
